services:
  backend:
    image: backend-stack
    pull_policy: never
    container_name: backend-stack
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  frontend:
    image: frontend-stack
    pull_policy: never
    container_name: frontend-stack
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "80:80"